server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APP_NAME:bookwise}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:bookwise_db}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID:ACcb4bed65b975e2349ca56c7c67c99d4f}
  auth:
    token: ${TWILIO_AUTH_TOKEN:612b2c42dc1f85ea7ed3e057eb0eefdf}
  phone:
    number: ${TWILIO_PHONE_NUMBER:+12562596972}