server:
  port: 8080

spring:

  application:
    name: bookwise

  datasource:
    url: jdbc:mysql://localhost:3306/bookwise
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  sql:
#    init:
#      mode: always




logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}